<div id="add">
	<form action="addsave">
		<label>Track new series<input type="text" name="stitle" /></label>
		<label><select name="newday">
				<option value="-1">Not updating</option>
				<option value="0">Sun</option>
				<option value="1">Mon</option>
				<option value="2">Tues</option>
				<option value="3">Wed</option>
				<option value="4">Thus</option>
				<option value="5">Fri</option>
				<option value="6">Sat</option>
		<input type="submit" />
		<br />
		<p class="helpful">Note: the series name needs to be the Crunchyroll series name, which is not necessarily the original title.</p>
		<p class="helpful">Note: Sometimes Crunchyroll updates during the middle of the day. You would need to set the day to the day after the day of the update.</p>
	</form>
</div>