<span id="error"><?=$this->error?></span>
<ul>
<?php 
$arr = getdate();
$day = $arr['wday'];
$day = (($day + 6) % 7);

if ($this->series) foreach ($this->series as $serie) { ?>
<li
	<?php if ($serie->newday == $day) {
		echo ' class="selected" ';
	}?>
	<?php if ($serie->newday == -1) {
		echo ' class="past" ';
	}?>
	>
	<a href="http://www.crunchyroll.com/<?
			$cseries = strtolower(trim(preg_replace('/[!;\/\?]/', '', $serie->stitle)));
$cseries = strtr($cseries, ' ', '-');
echo $cseries;
 ?>"><?=$serie->stitle?></a>: <a href="crfetchsave?seriesid=<?=$serie->id?>">Update now</a> Last Updated: <?=$serie->lastcheck?> <a href="delete?seriesid=<?=$serie->id?>">Stop updating</a>
</li>
<?php } ?>
</ul>
<p class="helpful">In the event the automatic site updater failed, you can push the button yourself, but not more than once a week. If a show updates at some point on Friday, on Saturday it will be marked in red above. If the show is not updating, it is marked in gray.</p>
<h3>Manual Data Entry</h3>
<form method="POST" action="/series2/emerg">
	<select name="seriesid">
<?php 
if ($this->series) foreach ($this->series as $serie) { ?>
		<option value="<?=$serie->id?>"><?=$serie->stitle?></option>
<?}?>	
	</select>
	<label>Episode: <input type="text" name="episode" /></label>
	<label>Crunchy episode URL: <input type="text" name="url" /></label>
	<input type="submit" />
</form>
<p class="helpful">The episode URL should be just the /episode part of the full URL.</p>
<h3>Update Update Date</h3>
<form action="delete">
	<select name="seriesid">
<?php 
if ($this->series) foreach ($this->series as $serie) { ?>
		<option value="<?=$serie->id?>"><?=$serie->stitle?></option>
<?}?>	
	</select>
<select name="newday">
		<option value="-1">Not updating</option>
		<option value="0">Sun</option>
		<option value="1">Mon</option>
		<option value="2">Tues</option>
		<option value="3">Wed</option>
		<option value="4">Thus</option>
		<option value="5">Fri</option>
		<option value="6">Sat</option>
<input type="submit" />
</form>
<p class="helpful">Note: Sometimes Crunchyroll updates during the middle of the day. You would need to set the day to the day after the update.</p>